# -------------------------------------------------------------------------
# create_calibration_project
# -------------------------------------------------------------------------
#' @title Create a SWAT calibration project
#'
#' @description
#' Creates a new SWAT calibration project by copying all required input files
#' from an existing \code{TxtInOut} folder into a new project directory. A
#' \code{Backup} subfolder is also created and populated with the same inputs
#' so original files can be safely restored during iterative calibration or
#' sensitivity analyses.
#'
#' @param swat_TxtInOut character. Path to the existing SWAT \code{TxtInOut}
#'   folder.
#' @param destination_dir character. Directory where the new project will be
#'   created. If \code{NULL}, defaults to the current working directory.
#' @param project_name character. Name for the new calibration project.
#' @param set_working_dir logical. If \code{TRUE} (default), sets the working
#'   directory to the new project's \code{TxtInOut} folder.
#'
#' @details
#' Output files typically generated by SWAT (e.g., \code{output.rch},
#' \code{output.sub}, \code{output.hru}, etc.) are excluded from the copy to
#' keep the project clean and reproducible from inputs.
#'
#' @return
#' Invisibly returns \code{NULL}. Prints a message with the path to the newly
#' created \code{TxtInOut} folder.
#'
#' @family Multiobjective calibration
#' @seealso
#' \link{run_swat} for executing SWAT runs,
#' \link{download_swat_exe} to obtain the SWAT executable (Windows only),
#' \link{setup_swat} to configure simulation period and outputs.
#'
#' @examples
#' \donttest{
#'   old_wd <- getwd()
#'   on.exit(setwd(old_wd), add = TRUE)
#'
#' # Write the example SWAT project into a temporary directory
#' tmpdir <- tempdir()
#' get_swat_example(tmpdir)
#'
#' # Create a calibration project (adds Backup) and set it as working directory
#' create_calibration_project(
#'   swat_TxtInOut   = file.path(tmpdir, "TxtInOut"),
#'   destination_dir = tmpdir,
#'   project_name    = "calib_project",
#'   set_working_dir = TRUE
#' )
#' }
#'
#' @export
create_calibration_project <- function(swat_TxtInOut, destination_dir = NULL,
                                       project_name, set_working_dir = TRUE) {

  # Check if the input path exists
  if (!file.exists(swat_TxtInOut)) {
    stop(paste(swat_TxtInOut, "path does not exist"))
  }

  # Verify if it is a valid SWAT project
  if (!file.exists(file.path(swat_TxtInOut, "file.cio"))) {
    stop(paste(swat_TxtInOut, "is not a SWAT project"))
  }

  # Use the working directory if destination_dir is NULL
  if (is.null(destination_dir)) {
    destination_dir <- getwd()
  } else if (!file.exists(destination_dir)) {
    stop(paste(destination_dir, "path does not exist"))
  }

  # Define project directories
  TxtInOut_path <- file.path(destination_dir, project_name, "TxtInOut")
  Backup_path <- file.path(TxtInOut_path, "Backup")

  # Create all necessary directories recursively
  dir.create(Backup_path, recursive = TRUE)

  # Files to copy (excluding SWAT output files)
  to_copy <- setdiff(list.files(swat_TxtInOut),
                     c("output.hru", "output.pst", "output.rch", "output.rsv",
                       "output.sed", "output.std", "output.sub", "watout.dat"))

  to_copy <- file.path(swat_TxtInOut, to_copy)

  # Copy files to TxtInOut and Backup
  file.copy(from = to_copy, to = TxtInOut_path, copy.mode = TRUE, overwrite = TRUE)
  file.copy(from = to_copy, to = Backup_path, copy.mode = TRUE, overwrite = TRUE)

  # Optionally set working directory to the created project
  if (set_working_dir) {
    setwd(TxtInOut_path)
  }

  # Print success message
  message(paste("The calibration project has been successfully created in",
                TxtInOut_path))

  invisible(NULL)
}
